from typing import List, Optional
from ..repositories.prekey_repo import PrekeyRepository
from ..models.keys import OneTimePrekey
import logging

logger = logging.getLogger(__name__)

class OneTimePrekeyManager:
    """
    Manages vast pools of single-use cryptographic prekeys.
    Defends against race conditions where two simultaneous connections try to consume the same key.
    """
    def __init__(self, repo: PrekeyRepository):
        self.repo = repo
        self.replenishment_threshold = 20 # Replenish when below this

    async def store_batch(self, user_id: int, device_id: str, keys_data: List[dict]):
        """
        Stores a batch of prekeys generated by the client.
        """
        opks = [
            OneTimePrekey(
                key_id=kd["key_id"],
                public_key_b64=kd["public_key_b64"]
            )
            for kd in keys_data
        ]
        await self.repo.insert_one_time_prekeys(user_id, device_id, opks)
        logger.info(f"Stored {len(opks)} OPKs for {device_id}")

    async def consume_key(self, user_id: int, device_id: str) -> Optional[OneTimePrekey]:
        """
        Atomically fetches and burns an OPK so it can never be used again.
        """
        opk = await self.repo.get_any_available_opk(user_id, device_id)
        if not opk:
            logger.warning(f"No available OPKs for {device_id}")
            return None
            
        success = await self.repo.consume_one_time_prekey(user_id, device_id, opk.key_id)
        if success:
            logger.info(f"Consumed OPK(ID={opk.key_id}) for {device_id}")
            return opk
            
        # Race condition! Someone else consumed it first. Return None and let caller retry.
        logger.warning(f"Race condition consuming OPK {opk.key_id}")
        return None

    async def needs_replenishment(self, user_id: int, device_id: str) -> bool:
        count = await self.repo.get_available_opk_count(user_id, device_id)
        return count < self.replenishment_threshold
