from enum import Enum

class HandshakeState(str, Enum):
    INITIALIZED = "INITIALIZED"
    BUNDLE_REQUESTED = "BUNDLE_REQUESTED"
    BUNDLE_RECEIVED = "BUNDLE_RECEIVED"
    BUNDLE_VALIDATED = "BUNDLE_VALIDATED"
    PREKEY_RESERVED = "PREKEY_RESERVED"
    SHARED_SECRET_DERIVED = "SHARED_SECRET_DERIVED"
    SESSION_CREATED = "SESSION_CREATED"
    COMPLETED = "COMPLETED"
    
    FAILED = "FAILED"
    ABORTED = "ABORTED"
    EXPIRED = "EXPIRED"

class SessionStatus(str, Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    TERMINATED = "TERMINATED"
